<?php


namespace App\Modules\Auth\Dto;


use App\Traits\SecureParams;

class UserParentDto extends BaseUserDto
{
      private int $relation_id;
      private string $job_place;
      private string $position;
      private string $birthday;
      private int $city_id;
      private string $street;
      private int $house_number;
      private int $apt;

      public function __construct(array $request)
      {
          parent::__construct($request);
          $this->city_id = SecureParams::filter($request['city_id']);
          $this->relation_id = SecureParams::filter($request['relation_id']);
          $this->job_place = SecureParams::filter($request['job_place']);
          $this->position = SecureParams::filter($request['position']);
          $this->birthday = SecureParams::filter($request['birthday']);
          $this->street = SecureParams::filter($request['street']);
          $this->house_number = SecureParams::filter($request['house_number']);
          $this->apt = SecureParams::filter($request['apt']);
      }

    public function toArray(): array
    {
        $data = parent::toArray(); // TODO: Change the autogenerated stub
        return array_merge($data,get_object_vars($this));
    }
}
