<?php


namespace App\Modules\Auth\Dto;


use App\Traits\SecureParams;

class UserChildDto extends BaseUserDto
{
    private int $city_id;
    private string $street;
    private int $house_number;
    private int $apt;
    private int $school_id;
    private int $class;
    private string $letter;
    private int $gender_id;
    private string $birthday;

    public function __construct(array $request)
    {
        parent::__construct($request);
        $this->city_id = SecureParams::filter($request['city_id']);
        $this->school_id = SecureParams::filter($request['school_id']);
        $this->class = SecureParams::filter($request['class']);
        $this->letter = SecureParams::filter($request['letter']);
        $this->gender_id = SecureParams::filter($request['gender_id']);
        $this->birthday = SecureParams::filter($request['birthday']);
        $this->street = SecureParams::filter($request['street']);
        $this->house_number = SecureParams::filter($request['house_number']);
        $this->apt = SecureParams::filter($request['apt']);
    }

    public function toArray(): array
    {
        $data = parent::toArray(); // TODO: Change the autogenerated stub
        return array_merge($data,get_object_vars($this));
    }
}
