<?php


namespace App\Modules\Auth\Dto;


use App\Traits\SecureParams;

class UserDashboardDto extends BaseUserDto
{
   private int $school_id;
   private string $class;
   private string $letter;
   private array $subjects;
   private ?int $city_id;
   private ?string $street;
   private ?int $house_number;
   private ?int $apt;

   public function __construct(array $request)
   {
       $this->school_id = SecureParams::filter($request['school_id']);
       $this->class = SecureParams::filter($request['class']);
       $this->letter = SecureParams::filter($request['letter']);
       $this->subjects = SecureParams::filter($request['subjects']);
       $this->city_id = null;
       if (isset($request['city_id'])) {
           $this->city_id = SecureParams::filter($request['city_id']);
       }
       $this->street = null;
       if (isset($request['street'])) {
           $this->street = SecureParams::filter($request['street']);
       }
       $this->house_number = null;
       if (isset($request['house_number'])) {
           $this->house_number = SecureParams::filter($request['house_number']);
       }
       $this->apt = null;
       if (isset($request['apt'])) {
           $this->apt = SecureParams::filter($request['apt']);
       }
       parent::__construct($request);
   }

   public function toArray(): array
   {
      $data = parent::toArray(); // TODO: Change the autogenerated stub
      return array_merge($data,get_object_vars($this));
   }
}
